### ISSUE TITLE
SyntaxError: Unexpected token 'export' when importing slate-table

### ISSUE THREAD

**Issue by MikhailKochkin** [nlulic/slate-table#2]
Description:
When trying to import the `slate-table` package in my editor in my Next.js application, I'm encountering the following error:

```
SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:128:18)
    at wrapSafe (node:internal/modules/cjs/loader:1280:20)
    at Module._compile (node:internal/modules/cjs/loader:1332:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at mod.require (/Users/mikhail/Desktop/BeSavvy_Code_Base/savvy-front/node_modules/next/dist/server/require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at slate-table (/Users/mikhail/Desktop/BeSavvy_Code_Base/savvy-front/.next/server/pages/blog.js:492:18)
    at __webpack_require__ (/Users/mikhail/Desktop/BeSavvy_Code_Base/savvy-front/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///./components/editor/Editor.js:31:70)
    at ./components/editor/Editor.js (/Users/mikhail/Desktop/BeSavvy_Code_Base/savvy-front/.next/server/components_editor_Editor_js.js:20:1)
    at Function.__webpack_require__ (/Users/mikhail/Desktop/BeSavvy_Code_Base/savvy-front/.next/server/webpack-runtime.js:33:43)
/Users/mikhail/Desktop/BeSavvy_Code_Base/savvy-front/node_modules/slate-table/dist/index.js:1
export * from "./table-cursor";
^^^^^^

```
Environment:
- Operating System: macOS (version 14.4.1 )
- Node.js version: v18.19.1 (also tried on LTS – v20.12.2)
- Next.js version: 14.1.4
- slate-table version: 0.1.0

Expected Behavior:
The Next.js application should start without any errors, and the `slate-table` package should be imported and used correctly.

Actual Behavior:
The application starts and works, but the error `SyntaxError: Unexpected token 'export'` is thrown every time when attempting to import the `slate-table` package.

Additional Information:
- I've tried transpiling the `slate-table` package using Babel, but the issue persists.
- The issue looks like the ES6 module syntax used by the `slate-table` package, which is not natively supported by my current Node.js version (v18.19.1). But I don't think this is the case and I can't just see the real problem.

Please let me know if you need any additional information or if there are any potential solutions or workarounds for this issue.

PS: It would be nice to resolve this issue because the package and documentation are great! I have been waiting for something like this for quite a while. And would like to see it develop!

**Comment by nlulic** [comment]
Hello @MikhailKochkin, thank you for creating a detailed issue. I have now bundled the package for both CJS and ESM and pushed a new version ([v0.1.1](https://github.com/nlulic/slate-table/releases/tag/v0.1.1)) to NPM. 

Could you please update slate-table to version 0.1.1 and let me know if this resolves the issue?

**Comment by MikhailKochkin** [comment]
Hello @nlulic,

Yes, I don't see any error messages any more. So I think the issue is resolved.

Thank you!

**Comment by nlulic** [comment]
Great! If you encounter any more problems feel free to raise another issue.

And thanks a lot for the encouragement, I hope to find some time soon to improve the library. :)
